# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/tools/Azure.GeneratorAgent/

pr:
  branches:
    include:
    - main
    - feature/*
    - release/*
    - hotfix/*
  paths:
    include:
    - sdk/tools/Azure.GeneratorAgent/

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: tools
    ArtifactName: packages
    Artifacts:
    - name: Azure.GeneratorAgent
      safeName: AzureGeneratorAgent
    MatrixConfigs:
    - Name: Generator_Net10_Only
      Path: sdk/tools/platform-generator-matrix.json
      Selection: sparse
      GenerateVMJobs: true